name: volga

services:
  db:
    image: postgres:15
    container_name: volga-db
    restart: always
    environment:
      POSTGRES_DB: volga
      POSTGRES_USER: volga
      POSTGRES_PASSWORD: volga
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U volga -d volga"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: volga-backend
    restart: always
    command: >
      sh -c "
      until python manage.py migrate; do
        echo 'Waiting for PostgreSQL...';
        sleep 1;
      done &&
      python manage.py collectstatic --noinput &&
      gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "
    volumes:
      - ./backend:/app
      - media_data:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_DB: volga
      POSTGRES_USER: volga
      POSTGRES_PASSWORD: volga
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  frontend:
    build: ./frontend
    container_name: volga-frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  media_data:
  static_data:
